services:
  mysql:
    image: mysql:8.0
    container_name: mysql1
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: ecommerce_admin
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: backend1
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_NAME=ecommerce_db
      - DB_USER=ecommerce_admin
      - DB_PASSWORD=password123
    volumes:
      - ./backend:/app  # Sync backend files with container
      - /app/node_modules  # Prevents overwriting dependencies
      - uploads_data:/app/uploads # persistent uploads
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend1
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mysql-data:
  uploads_data:
